In [4]:
import requests

In [5]:
import json

In [6]:
target_url = 'https://covid19.ddc.moph.go.th/api/Cases/timeline-cases-all'

raw_json = requests.get(target_url).text
data = json.loads(raw_json)

In [7]:
t ='https://covid19.ddc.moph.go.th/api/Cases/timeline-cases-all'
raw_json = requests.get(target_url).text
data = json.loads(raw_json)

In [8]:
data

[{'txn_date': '2021-04-01',
  'new_case': 26,
  'total_case': 28889,
  'new_case_excludeabroad': 21,
  'total_case_excludeabroad': 25800,
  'new_death': 0,
  'total_death': 94,
  'new_recovered': 122,
  'total_recovered': 27767,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-02',
  'new_case': 58,
  'total_case': 28947,
  'new_case_excludeabroad': 45,
  'total_case_excludeabroad': 25845,
  'new_death': 0,
  'total_death': 94,
  'new_recovered': 58,
  'total_recovered': 27825,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-03',
  'new_case': 84,
  'total_case': 29031,
  'new_case_excludeabroad': 69,
  'total_case_excludeabroad': 25914,
  'new_death': 1,
  'total_death': 95,
  'new_recovered': 62,
  'total_recovered': 27887,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-04',
  'new_case': 96,
  'total_case': 29127,
  'new_case_excludeabroad': 87,
  'total_case_excludeabroad': 26001,
  'new_death': 0,
  'total_death': 95,
  'new_recovered': 106,
  'total_recovered': 27993,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-05',
  'new_case': 194,
  'total_case': 29321,
  'new_case_excludeabroad': 182,
  'total_case_excludeabroad': 26183,
  'new_death': 0,
  'total_death': 95,
  'new_recovered': 66,
  'total_recovered': 28059,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-06',
  'new_case': 250,
  'total_case': 29571,
  'new_case_excludeabroad': 245,
  'total_case_excludeabroad': 26428,
  'new_death': 0,
  'total_death': 95,
  'new_recovered': 108,
  'total_recovered': 28167,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-07',
  'new_case': 334,
  'total_case': 29905,
  'new_case_excludeabroad': 327,
  'total_case_excludeabroad': 26755,
  'new_death': 0,
  'total_death': 95,
  'new_recovered': 121,
  'total_recovered': 28288,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-08',
  'new_case': 405,
  'total_case': 30310,
  'new_case_excludeabroad': 391,
  'total_case_excludeabroad': 27146,
  'new_death': 0,
  'total_death': 95,
  'new_recovered': 32,
  'total_recovered': 28320,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-09',
  'new_case': 559,
  'total_case': 30869,
  'new_case_excludeabroad': 549,
  'total_case_excludeabroad': 27695,
  'new_death': 1,
  'total_death': 96,
  'new_recovered': 27,
  'total_recovered': 28347,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-10',
  'new_case': 789,
  'total_case': 31658,
  'new_case_excludeabroad': 781,
  'total_case_excludeabroad': 28476,
  'new_death': 1,
  'total_death': 97,
  'new_recovered': 33,
  'total_recovered': 28380,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-11',
  'new_case': 967,
  'total_case': 32625,
  'new_case_excludeabroad': 964,
  'total_case_excludeabroad': 29440,
  'new_death': 0,
  'total_death': 97,
  'new_recovered': 53,
  'total_recovered': 28433,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-12',
  'new_case': 985,
  'total_case': 33610,
  'new_case_excludeabroad': 980,
  'total_case_excludeabroad': 30420,
  'new_death': 0,
  'total_death': 97,
  'new_recovered': 34,
  'total_recovered': 28467,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-13',
  'new_case': 965,
  'total_case': 34575,
  'new_case_excludeabroad': 956,
  'total_case_excludeabroad': 31376,
  'new_death': 0,
  'total_death': 97,
  'new_recovered': 40,
  'total_recovered': 28507,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-14',
  'new_case': 1338,
  'total_case': 35913,
  'new_case_excludeabroad': 1330,
  'total_case_excludeabroad': 32706,
  'new_death': 0,
  'total_death': 97,
  'new_recovered': 34,
  'total_recovered': 28541,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-15',
  'new_case': 1543,
  'total_case': 37456,
  'new_case_excludeabroad': 1540,
  'total_case_excludeabroad': 34246,
  'new_death': 0,
  'total_death': 97,
  'new_recovered': 61,
  'total_recovered': 28602,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-16',
  'new_case': 1582,
  'total_case': 39038,
  'new_case_excludeabroad': 1576,
  'total_case_excludeabroad': 35822,
  'new_death': 3,
  'total_death': 100,
  'new_recovered': 97,
  'total_recovered': 28699,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-17',
  'new_case': 1547,
  'total_case': 40585,
  'new_case_excludeabroad': 1544,
  'total_case_excludeabroad': 37366,
  'new_death': 0,
  'total_death': 100,
  'new_recovered': 90,
  'total_recovered': 28789,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-18',
  'new_case': 1767,
  'total_case': 42352,
  'new_case_excludeabroad': 1765,
  'total_case_excludeabroad': 39131,
  'new_death': 1,
  'total_death': 101,
  'new_recovered': 113,
  'total_recovered': 28902,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-19',
  'new_case': 1390,
  'total_case': 43742,
  'new_case_excludeabroad': 1386,
  'total_case_excludeabroad': 40517,
  'new_death': 3,
  'total_death': 104,
  'new_recovered': 104,
  'total_recovered': 29006,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-20',
  'new_case': 1443,
  'total_case': 45185,
  'new_case_excludeabroad': 1441,
  'total_case_excludeabroad': 41958,
  'new_death': 4,
  'total_death': 108,
  'new_recovered': 171,
  'total_recovered': 29177,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-21',
  'new_case': 1458,
  'total_case': 46643,
  'new_case_excludeabroad': 1454,
  'total_case_excludeabroad': 43412,
  'new_death': 2,
  'total_death': 110,
  'new_recovered': 413,
  'total_recovered': 29590,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-22',
  'new_case': 1470,
  'total_case': 48113,
  'new_case_excludeabroad': 1470,
  'total_case_excludeabroad': 44882,
  'new_death': 7,
  'total_death': 117,
  'new_recovered': 477,
  'total_recovered': 30067,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-23',
  'new_case': 2070,
  'total_case': 50183,
  'new_case_excludeabroad': 2062,
  'total_case_excludeabroad': 46944,
  'new_death': 4,
  'total_death': 121,
  'new_recovered': 341,
  'total_recovered': 30408,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-24',
  'new_case': 2839,
  'total_case': 53022,
  'new_case_excludeabroad': 2827,
  'total_case_excludeabroad': 49771,
  'new_death': 8,
  'total_death': 129,
  'new_recovered': 377,
  'total_recovered': 30785,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-25',
  'new_case': 2438,
  'total_case': 55460,
  'new_case_excludeabroad': 2433,
  'total_case_excludeabroad': 52204,
  'new_death': 11,
  'total_death': 140,
  'new_recovered': 547,
  'total_recovered': 31332,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-26',
  'new_case': 2048,
  'total_case': 57508,
  'new_case_excludeabroad': 2037,
  'total_case_excludeabroad': 54241,
  'new_death': 8,
  'total_death': 148,
  'new_recovered': 480,
  'total_recovered': 31812,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-27',
  'new_case': 2179,
  'total_case': 59687,
  'new_case_excludeabroad': 2174,
  'total_case_excludeabroad': 56415,
  'new_death': 15,
  'total_death': 163,
  'new_recovered': 1958,
  'total_recovered': 33770,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-28',
  'new_case': 2012,
  'total_case': 61699,
  'new_case_excludeabroad': 2001,
  'total_case_excludeabroad': 58416,
  'new_death': 15,
  'total_death': 178,
  'new_recovered': 851,
  'total_recovered': 34621,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-29',
  'new_case': 1871,
  'total_case': 63570,
  'new_case_excludeabroad': 1864,
  'total_case_excludeabroad': 60280,
  'new_death': 10,
  'total_death': 188,
  'new_recovered': 992,
  'total_recovered': 35613,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-04-30',
  'new_case': 1583,
  'total_case': 65153,
  'new_case_excludeabroad': 1579,
  'total_case_excludeabroad': 61859,
  'new_death': 15,
  'total_death': 203,
  'new_recovered': 860,
  'total_recovered': 36473,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-01',
  'new_case': 1891,
  'total_case': 67044,
  'new_case_excludeabroad': 1884,
  'total_case_excludeabroad': 63743,
  'new_death': 21,
  'total_death': 224,
  'new_recovered': 1821,
  'total_recovered': 38294,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-02',
  'new_case': 1940,
  'total_case': 68984,
  'new_case_excludeabroad': 1930,
  'total_case_excludeabroad': 65673,
  'new_death': 21,
  'total_death': 245,
  'new_recovered': 1183,
  'total_recovered': 39477,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-03',
  'new_case': 2041,
  'total_case': 71025,
  'new_case_excludeabroad': 2040,
  'total_case_excludeabroad': 67713,
  'new_death': 31,
  'total_death': 276,
  'new_recovered': 1726,
  'total_recovered': 41203,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-04',
  'new_case': 1763,
  'total_case': 72788,
  'new_case_excludeabroad': 1750,
  'total_case_excludeabroad': 69463,
  'new_death': 27,
  'total_death': 303,
  'new_recovered': 1490,
  'total_recovered': 42693,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-05',
  'new_case': 2112,
  'total_case': 74900,
  'new_case_excludeabroad': 2107,
  'total_case_excludeabroad': 71570,
  'new_death': 15,
  'total_death': 318,
  'new_recovered': 1886,
  'total_recovered': 44579,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-06',
  'new_case': 1911,
  'total_case': 76811,
  'new_case_excludeabroad': 1902,
  'total_case_excludeabroad': 73472,
  'new_death': 18,
  'total_death': 336,
  'new_recovered': 2435,
  'total_recovered': 47014,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-07',
  'new_case': 2044,
  'total_case': 78855,
  'new_case_excludeabroad': 2040,
  'total_case_excludeabroad': 75512,
  'new_death': 27,
  'total_death': 363,
  'new_recovered': 2377,
  'total_recovered': 49391,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-08',
  'new_case': 2419,
  'total_case': 81274,
  'new_case_excludeabroad': 2409,
  'total_case_excludeabroad': 77921,
  'new_death': 19,
  'total_death': 382,
  'new_recovered': 2247,
  'total_recovered': 51638,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-09',
  'new_case': 2101,
  'total_case': 83375,
  'new_case_excludeabroad': 2086,
  'total_case_excludeabroad': 80007,
  'new_death': 17,
  'total_death': 399,
  'new_recovered': 2186,
  'total_recovered': 53824,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-10',
  'new_case': 1630,
  'total_case': 85005,
  'new_case_excludeabroad': 1622,
  'total_case_excludeabroad': 81629,
  'new_death': 22,
  'total_death': 421,
  'new_recovered': 1603,
  'total_recovered': 55427,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-11',
  'new_case': 1919,
  'total_case': 86924,
  'new_case_excludeabroad': 1902,
  'total_case_excludeabroad': 83531,
  'new_death': 31,
  'total_death': 452,
  'new_recovered': 1829,
  'total_recovered': 57256,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-12',
  'new_case': 1983,
  'total_case': 88907,
  'new_case_excludeabroad': 1974,
  'total_case_excludeabroad': 85505,
  'new_death': 34,
  'total_death': 486,
  'new_recovered': 2006,
  'total_recovered': 59262,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-13',
  'new_case': 4887,
  'total_case': 93794,
  'new_case_excludeabroad': 4871,
  'total_case_excludeabroad': 90376,
  'new_death': 32,
  'total_death': 518,
  'new_recovered': 1572,
  'total_recovered': 60834,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-14',
  'new_case': 2256,
  'total_case': 96050,
  'new_case_excludeabroad': 2251,
  'total_case_excludeabroad': 92627,
  'new_death': 30,
  'total_death': 548,
  'new_recovered': 1701,
  'total_recovered': 62535,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-15',
  'new_case': 3095,
  'total_case': 99145,
  'new_case_excludeabroad': 3092,
  'total_case_excludeabroad': 95719,
  'new_death': 17,
  'total_death': 565,
  'new_recovered': 1351,
  'total_recovered': 63886,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-16',
  'new_case': 2302,
  'total_case': 101447,
  'new_case_excludeabroad': 2279,
  'total_case_excludeabroad': 97998,
  'new_death': 24,
  'total_death': 589,
  'new_recovered': 2136,
  'total_recovered': 66022,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-17',
  'new_case': 9635,
  'total_case': 111082,
  'new_case_excludeabroad': 9626,
  'total_case_excludeabroad': 107624,
  'new_death': 25,
  'total_death': 614,
  'new_recovered': 1397,
  'total_recovered': 67419,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-18',
  'new_case': 2473,
  'total_case': 113555,
  'new_case_excludeabroad': 2450,
  'total_case_excludeabroad': 110074,
  'new_death': 35,
  'total_death': 649,
  'new_recovered': 2718,
  'total_recovered': 70137,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-19',
  'new_case': 3394,
  'total_case': 116949,
  'new_case_excludeabroad': 3377,
  'total_case_excludeabroad': 113451,
  'new_death': 29,
  'total_death': 678,
  'new_recovered': 4450,
  'total_recovered': 74587,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-20',
  'new_case': 2636,
  'total_case': 119585,
  'new_case_excludeabroad': 2578,
  'total_case_excludeabroad': 116029,
  'new_death': 25,
  'total_death': 703,
  'new_recovered': 2268,
  'total_recovered': 76855,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-21',
  'new_case': 3481,
  'total_case': 123066,
  'new_case_excludeabroad': 3469,
  'total_case_excludeabroad': 119498,
  'new_death': 32,
  'total_death': 735,
  'new_recovered': 2868,
  'total_recovered': 79723,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-22',
  'new_case': 3052,
  'total_case': 126118,
  'new_case_excludeabroad': 3011,
  'total_case_excludeabroad': 122509,
  'new_death': 24,
  'total_death': 759,
  'new_recovered': 2900,
  'total_recovered': 82623,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-23',
  'new_case': 3382,
  'total_case': 129500,
  'new_case_excludeabroad': 3377,
  'total_case_excludeabroad': 125886,
  'new_death': 17,
  'total_death': 776,
  'new_recovered': 2131,
  'total_recovered': 84754,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-24',
  'new_case': 2713,
  'total_case': 132213,
  'new_case_excludeabroad': 2664,
  'total_case_excludeabroad': 128550,
  'new_death': 30,
  'total_death': 806,
  'new_recovered': 1565,
  'total_recovered': 86319,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-25',
  'new_case': 3226,
  'total_case': 135439,
  'new_case_excludeabroad': 3207,
  'total_case_excludeabroad': 131757,
  'new_death': 26,
  'total_death': 832,
  'new_recovered': 3094,
  'total_recovered': 89413,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-26',
  'new_case': 2455,
  'total_case': 137894,
  'new_case_excludeabroad': 2439,
  'total_case_excludeabroad': 134196,
  'new_death': 41,
  'total_death': 873,
  'new_recovered': 2571,
  'total_recovered': 91984,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-27',
  'new_case': 3323,
  'total_case': 141217,
  'new_case_excludeabroad': 3302,
  'total_case_excludeabroad': 137498,
  'new_death': 47,
  'total_death': 920,
  'new_recovered': 2063,
  'total_recovered': 94047,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-28',
  'new_case': 3759,
  'total_case': 144976,
  'new_case_excludeabroad': 3741,
  'total_case_excludeabroad': 141239,
  'new_death': 34,
  'total_death': 954,
  'new_recovered': 4044,
  'total_recovered': 98091,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-29',
  'new_case': 4803,
  'total_case': 149779,
  'new_case_excludeabroad': 4752,
  'total_case_excludeabroad': 145991,
  'new_death': 34,
  'total_death': 988,
  'new_recovered': 4439,
  'total_recovered': 102530,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-30',
  'new_case': 4528,
  'total_case': 154307,
  'new_case_excludeabroad': 4501,
  'total_case_excludeabroad': 150492,
  'new_death': 24,
  'total_death': 1012,
  'new_recovered': 2933,
  'total_recovered': 105463,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-05-31',
  'new_case': 5485,
  'total_case': 159792,
  'new_case_excludeabroad': 5428,
  'total_case_excludeabroad': 155920,
  'new_death': 19,
  'total_death': 1031,
  'new_recovered': 3101,
  'total_recovered': 108564,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-01',
  'new_case': 2230,
  'total_case': 162022,
  'new_case_excludeabroad': 2209,
  'total_case_excludeabroad': 158129,
  'new_death': 38,
  'total_death': 1069,
  'new_recovered': 3390,
  'total_recovered': 111954,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-02',
  'new_case': 3440,
  'total_case': 165462,
  'new_case_excludeabroad': 3425,
  'total_case_excludeabroad': 161554,
  'new_death': 38,
  'total_death': 1107,
  'new_recovered': 2843,
  'total_recovered': 114797,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-03',
  'new_case': 3886,
  'total_case': 169348,
  'new_case_excludeabroad': 3837,
  'total_case_excludeabroad': 165391,
  'new_death': 39,
  'total_death': 1146,
  'new_recovered': 3626,
  'total_recovered': 118423,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-04',
  'new_case': 2631,
  'total_case': 171979,
  'new_case_excludeabroad': 2580,
  'total_case_excludeabroad': 167971,
  'new_death': 31,
  'total_death': 1177,
  'new_recovered': 2493,
  'total_recovered': 120916,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-05',
  'new_case': 2817,
  'total_case': 174796,
  'new_case_excludeabroad': 2761,
  'total_case_excludeabroad': 170732,
  'new_death': 36,
  'total_death': 1213,
  'new_recovered': 3396,
  'total_recovered': 124312,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-06',
  'new_case': 2671,
  'total_case': 177467,
  'new_case_excludeabroad': 2588,
  'total_case_excludeabroad': 173320,
  'new_death': 23,
  'total_death': 1236,
  'new_recovered': 2424,
  'total_recovered': 126736,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-07',
  'new_case': 2419,
  'total_case': 179886,
  'new_case_excludeabroad': 2387,
  'total_case_excludeabroad': 175707,
  'new_death': 33,
  'total_death': 1269,
  'new_recovered': 2999,
  'total_recovered': 129735,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-08',
  'new_case': 2662,
  'total_case': 182548,
  'new_case_excludeabroad': 2646,
  'total_case_excludeabroad': 178353,
  'new_death': 29,
  'total_death': 1298,
  'new_recovered': 2483,
  'total_recovered': 132218,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-09',
  'new_case': 2680,
  'total_case': 185228,
  'new_case_excludeabroad': 2669,
  'total_case_excludeabroad': 181022,
  'new_death': 34,
  'total_death': 1332,
  'new_recovered': 4253,
  'total_recovered': 136471,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-10',
  'new_case': 2310,
  'total_case': 187538,
  'new_case_excludeabroad': 2272,
  'total_case_excludeabroad': 183294,
  'new_death': 43,
  'total_death': 1375,
  'new_recovered': 3035,
  'total_recovered': 139506,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-11',
  'new_case': 2290,
  'total_case': 189828,
  'new_case_excludeabroad': 2260,
  'total_case_excludeabroad': 185554,
  'new_death': 27,
  'total_death': 1402,
  'new_recovered': 5711,
  'total_recovered': 145217,
  'update_date': '2021-09-01 07:40:49'},
 {'txn_date': '2021-06-12',
  'new_case': 3277,
  'total_case': 193105,

In [9]:
type(data)

list

In [10]:
import pandas as pd
df = pd.DataFrame(data)

In [11]:
df.head()

,txn_date,new_case,total_case,new_case_excludeabroad,total_case_excludeabroad,new_death,total_death,new_recovered,total_recovered,update_date
0,2021-04-01,26,28889,21,25800,0,94,122,27767,2021-09-01 07:40:49
1,2021-04-02,58,28947,45,25845,0,94,58,27825,2021-09-01 07:40:49
2,2021-04-03,84,29031,69,25914,1,95,62,27887,2021-09-01 07:40:49
3,2021-04-04,96,29127,87,26001,0,95,106,27993,2021-09-01 07:40:49
4,2021-04-05,194,29321,182,26183,0,95,66,28059,2021-09-01 07:40:49

In [12]:
df.columns

Index(['txn_date', 'new_case', 'total_case', 'new_case_excludeabroad',
       'total_case_excludeabroad', 'new_death', 'total_death', 'new_recovered',
       'total_recovered', 'update_date'],
      dtype='object')

In [13]:
df.drop(columns=['new_case_excludeabroad', 'total_case_excludeabroad','new_death', 'total_death','update_date'],inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   txn_date         253 non-null    object
 1   new_case         253 non-null    int64
 2   total_case       253 non-null    int64
 3   new_recovered    253 non-null    int64
 4   total_recovered  253 non-null    int64
dtypes: int64(4), object(1)
memory usage: 10.0+ KB

In [15]:
# df.agg(['max','min','mean','std','median'])

In [16]:
# find ratio
a = round(((df['new_recovered']/df['total_case'])*100),2)
a

0      0.42
1      0.20
2      0.21
3      0.36
4      0.23
       ...
248    0.29
249    0.30
250    0.28
251    0.27
252    0.37
Length: 253, dtype: float64

In [17]:
b = round(((df['new_case']/df['total_case'])*100),2)
b

0      0.09
1      0.20
2      0.29
3      0.33
4      0.66
       ...
248    0.22
249    0.19
250    0.16
251    0.17
252    0.19
Length: 253, dtype: float64

In [18]:
# df1 = pd.concat([a, b], axis=1, ignore_index=True)
# df1

In [19]:
d = {'Date': df['txn_date'],'recovered_%': a, 'new_case_%':b} 
df1 = pd.DataFrame(d)
df1

           Date  recovered_%  new_case_%
0    2021-04-01         0.42        0.09
1    2021-04-02         0.20        0.20
2    2021-04-03         0.21        0.29
3    2021-04-04         0.36        0.33
4    2021-04-05         0.23        0.66
..          ...          ...         ...
248  2021-12-05         0.29        0.22
249  2021-12-06         0.30        0.19
250  2021-12-07         0.28        0.16
251  2021-12-08         0.27        0.17
252  2021-12-09         0.37        0.19

[253 rows x 3 columns]

In [20]:
df1.Date[0:]

0      2021-04-01
1      2021-04-02
2      2021-04-03
3      2021-04-04
4      2021-04-05
          ...
248    2021-12-05
249    2021-12-06
250    2021-12-07
251    2021-12-08
252    2021-12-09
Name: Date, Length: 253, dtype: object

In [21]:
json_data = df1.to_json(orient="records")
type(json_data)

str

In [22]:
json_data

'[{"Date":"2021-04-01","recovered_%":0.42,"new_case_%":0.09},{"Date":"2021-04-02","recovered_%":0.2,"new_case_%":0.2},{"Date":"2021-04-03","recovered_%":0.21,"new_case_%":0.29},{"Date":"2021-04-04","recovered_%":0.36,"new_case_%":0.33},{"Date":"2021-04-05","recovered_%":0.23,"new_case_%":0.66},{"Date":"2021-04-06","recovered_%":0.37,"new_case_%":0.85},{"Date":"2021-04-07","recovered_%":0.4,"new_case_%":1.12},{"Date":"2021-04-08","recovered_%":0.11,"new_case_%":1.34},{"Date":"2021-04-09","recovered_%":0.09,"new_case_%":1.81},{"Date":"2021-04-10","recovered_%":0.1,"new_case_%":2.49},{"Date":"2021-04-11","recovered_%":0.16,"new_case_%":2.96},{"Date":"2021-04-12","recovered_%":0.1,"new_case_%":2.93},{"Date":"2021-04-13","recovered_%":0.12,"new_case_%":2.79},{"Date":"2021-04-14","recovered_%":0.09,"new_case_%":3.73},{"Date":"2021-04-15","recovered_%":0.16,"new_case_%":4.12},{"Date":"2021-04-16","recovered_%":0.25,"new_case_%":4.05},{"Date":"2021-04-17","recovered_%":0.22,"new_case_%":3.81},{"Date":"2021-04-18","recovered_%":0.27,"new_case_%":4.17},{"Date":"2021-04-19","recovered_%":0.24,"new_case_%":3.18},{"Date":"2021-04-20","recovered_%":0.38,"new_case_%":3.19},{"Date":"2021-04-21","recovered_%":0.89,"new_case_%":3.13},{"Date":"2021-04-22","recovered_%":0.99,"new_case_%":3.06},{"Date":"2021-04-23","recovered_%":0.68,"new_case_%":4.12},{"Date":"2021-04-24","recovered_%":0.71,"new_case_%":5.35},{"Date":"2021-04-25","recovered_%":0.99,"new_case_%":4.4},{"Date":"2021-04-26","recovered_%":0.83,"new_case_%":3.56},{"Date":"2021-04-27","recovered_%":3.28,"new_case_%":3.65},{"Date":"2021-04-28","recovered_%":1.38,"new_case_%":3.26},{"Date":"2021-04-29","recovered_%":1.56,"new_case_%":2.94},{"Date":"2021-04-30","recovered_%":1.32,"new_case_%":2.43},{"Date":"2021-05-01","recovered_%":2.72,"new_case_%":2.82},{"Date":"2021-05-02","recovered_%":1.71,"new_case_%":2.81},{"Date":"2021-05-03","recovered_%":2.43,"new_case_%":2.87},{"Date":"2021-05-04","recovered_%":2.05,"new_case_%":2.42},{"Date":"2021-05-05","recovered_%":2.52,"new_case_%":2.82},{"Date":"2021-05-06","recovered_%":3.17,"new_case_%":2.49},{"Date":"2021-05-07","recovered_%":3.01,"new_case_%":2.59},{"Date":"2021-05-08","recovered_%":2.76,"new_case_%":2.98},{"Date":"2021-05-09","recovered_%":2.62,"new_case_%":2.52},{"Date":"2021-05-10","recovered_%":1.89,"new_case_%":1.92},{"Date":"2021-05-11","recovered_%":2.1,"new_case_%":2.21},{"Date":"2021-05-12","recovered_%":2.26,"new_case_%":2.23},{"Date":"2021-05-13","recovered_%":1.68,"new_case_%":5.21},{"Date":"2021-05-14","recovered_%":1.77,"new_case_%":2.35},{"Date":"2021-05-15","recovered_%":1.36,"new_case_%":3.12},{"Date":"2021-05-16","recovered_%":2.11,"new_case_%":2.27},{"Date":"2021-05-17","recovered_%":1.26,"new_case_%":8.67},{"Date":"2021-05-18","recovered_%":2.39,"new_case_%":2.18},{"Date":"2021-05-19","recovered_%":3.81,"new_case_%":2.9},{"Date":"2021-05-20","recovered_%":1.9,"new_case_%":2.2},{"Date":"2021-05-21","recovered_%":2.33,"new_case_%":2.83},{"Date":"2021-05-22","recovered_%":2.3,"new_case_%":2.42},{"Date":"2021-05-23","recovered_%":1.65,"new_case_%":2.61},{"Date":"2021-05-24","recovered_%":1.18,"new_case_%":2.05},{"Date":"2021-05-25","recovered_%":2.28,"new_case_%":2.38},{"Date":"2021-05-26","recovered_%":1.86,"new_case_%":1.78},{"Date":"2021-05-27","recovered_%":1.46,"new_case_%":2.35},{"Date":"2021-05-28","recovered_%":2.79,"new_case_%":2.59},{"Date":"2021-05-29","recovered_%":2.96,"new_case_%":3.21},{"Date":"2021-05-30","recovered_%":1.9,"new_case_%":2.93},{"Date":"2021-05-31","recovered_%":1.94,"new_case_%":3.43},{"Date":"2021-06-01","recovered_%":2.09,"new_case_%":1.38},{"Date":"2021-06-02","recovered_%":1.72,"new_case_%":2.08},{"Date":"2021-06-03","recovered_%":2.14,"new_case_%":2.29},{"Date":"2021-06-04","recovered_%":1.45,"new_case_%":1.53},{"Date":"2021-06-05","recovered_%":1.94,"new_case_%":1.61},{"Date":"2021-06-06","recovered_%":1.37,"new_case_%":1.51},{"Date":"2021-06-07","recovered_%":1.67,"new_case_%":1.34},{"Date":"2021-06-08","recovered_%":1.36,"new_case_%":1.46},{"Date":"2021-06-09","recovered_%":2.3,"new_case_%":1.45},{"Date":"2021-06-10","recovered_%":1.62,"new_case_%":1.23},{"Date":"2021-06-11","recovered_%":3.01,"new_case_%":1.21},{"Date":"2021-06-12","recovered_%":2.73,"new_case_%":1.7},{"Date":"2021-06-13","recovered_%":2.11,"new_case_%":1.43},{"Date":"2021-06-14","recovered_%":1.77,"new_case_%":1.68},{"Date":"2021-06-15","recovered_%":2.36,"new_case_%":1.48},{"Date":"2021-06-16","recovered_%":2.42,"new_case_%":1.14},{"Date":"2021-06-17","recovered_%":2.24,"new_case_%":1.51},{"Date":"2021-06-18","recovered_%":1.94,"new_case_%":1.45},{"Date":"2021-06-19","recovered_%":2.31,"new_case_%":1.71},{"Date":"2021-06-20","recovered_%":1.1,"new_case_%":1.69},{"Date":"2021-06-21","recovered_%":0.92,"new_case_%":1.43},{"Date":"2021-06-22","recovered_%":0.91,"new_case_%":1.8},{"Date":"2021-06-23","recovered_%":0.85,"new_case_%":1.39},{"Date":"2021-06-24","recovered_%":0.68,"new_case_%":1.77},{"Date":"2021-06-25","recovered_%":0.74,"new_case_%":1.54},{"Date":"2021-06-26","recovered_%":1.48,"new_case_%":1.73},{"Date":"2021-06-27","recovered_%":0.92,"new_case_%":1.63},{"Date":"2021-06-28","recovered_%":1.34,"new_case_%":2.16},{"Date":"2021-06-29","recovered_%":1.1,"new_case_%":1.83},{"Date":"2021-06-30","recovered_%":0.93,"new_case_%":1.85},{"Date":"2021-07-01","recovered_%":1.22,"new_case_%":2.09},{"Date":"2021-07-02","recovered_%":1.34,"new_case_%":2.25},{"Date":"2021-07-03","recovered_%":1.14,"new_case_%":2.25},{"Date":"2021-07-04","recovered_%":1.2,"new_case_%":2.09},{"Date":"2021-07-05","recovered_%":0.88,"new_case_%":2.13},{"Date":"2021-07-06","recovered_%":1.22,"new_case_%":1.84},{"Date":"2021-07-07","recovered_%":1.38,"new_case_%":2.16},{"Date":"2021-07-08","recovered_%":1.62,"new_case_%":2.29},{"Date":"2021-07-09","recovered_%":1.24,"new_case_%":2.92},{"Date":"2021-07-10","recovered_%":1.18,"new_case_%":2.85},{"Date":"2021-07-11","recovered_%":1.2,"new_case_%":2.84},{"Date":"2021-07-12","recovered_%":1.07,"new_case_%":2.51},{"Date":"2021-07-13","recovered_%":1.07,"new_case_%":2.46},{"Date":"2021-07-14","recovered_%":1.41,"new_case_%":2.57},{"Date":"2021-07-15","recovered_%":1.49,"new_case_%":2.47},{"Date":"2021-07-16","recovered_%":1.5,"new_case_%":2.54},{"Date":"2021-07-17","recovered_%":1.61,"new_case_%":2.57},{"Date":"2021-07-18","recovered_%":1.42,"new_case_%":2.83},{"Date":"2021-07-19","recovered_%":1.38,"new_case_%":2.84},{"Date":"2021-07-20","recovered_%":1.54,"new_case_%":2.65},{"Date":"2021-07-21","recovered_%":1.88,"new_case_%":2.96},{"Date":"2021-07-22","recovered_%":1.75,"new_case_%":3.01},{"Date":"2021-07-23","recovered_%":1.66,"new_case_%":3.12},{"Date":"2021-07-24","recovered_%":1.58,"new_case_%":2.96},{"Date":"2021-07-25","recovered_%":1.39,"new_case_%":3.08},{"Date":"2021-07-26","recovered_%":1.32,"new_case_%":3.0},{"Date":"2021-07-27","recovered_%":1.74,"new_case_%":2.69},{"Date":"2021-07-28","recovered_%":1.85,"new_case_%":3.04},{"Date":"2021-07-29","recovered_%":1.75,"new_case_%":3.15},{"Date":"2021-07-30","recovered_%":1.85,"new_case_%":3.0},{"Date":"2021-07-31","recovered_%":1.8,"new_case_%":3.17},{"Date":"2021-08-01","recovered_%":2.18,"new_case_%":2.93},{"Date":"2021-08-02","recovered_%":2.2,"new_case_%":2.84},{"Date":"2021-08-03","recovered_%":2.85,"new_case_%":2.9},{"Date":"2021-08-04","recovered_%":2.67,"new_case_%":3.0},{"Date":"2021-08-05","recovered_%":2.59,"new_case_%":3.02},{"Date":"2021-08-06","recovered_%":3.1,"new_case_%":2.99},{"Date":"2021-08-07","recovered_%":2.87,"new_case_%":2.97},{"Date":"2021-08-08","recovered_%":2.45,"new_case_%":2.64},{"Date":"2021-08-09","recovered_%":2.55,"new_case_%":2.53},{"Date":"2021-08-10","recovered_%":2.87,"new_case_%":2.49},{"Date":"2021-08-11","recovered_%":2.69,"new_case_%":2.58},{"Date":"2021-08-12","recovered_%":2.82,"new_case_%":2.71},{"Date":"2021-08-13","recovered_%":2.33,"new_case_%":2.71},{"Date":"2021-08-14","recovered_%":2.67,"new_case_%":2.49},{"Date":"2021-08-15","recovered_%":2.33,"new_case_%":2.41},{"Date":"2021-08-16","recovered_%":2.26,"new_case_%":2.28},{"Date":"2021-08-17","recovered_%":2.19,"new_case_%":2.12},{"Date":"2021-08-18","recovered_%":2.34,"new_case_%":2.12},{"Date":"2021-08-19","recovered_%":2.24,"new_case_%":2.11},{"Date":"2021-08-20","recovered_%":2.03,"new_case_%":1.97},{"Date":"2021-08-21","recovered_%":2.25,"new_case_%":2.0},{"Date":"2021-08-22","recovered_%":1.97,"new_case_%":1.81},{"Date":"2021-08-23","recovered_%":2.07,"new_case_%":1.64},{"Date":"2021-08-24","recovered_%":1.85,"new_case_%":1.58},{"Date":"2021-08-25","recovered_%":1.92,"new_case_%":1.67},{"Date":"2021-08-26","recovered_%":1.84,"new_case_%":1.65},{"Date":"2021-08-27","recovered_%":1.77,"new_case_%":1.64},{"Date":"2021-08-28","recovered_%":1.77,"new_case_%":1.55},{"Date":"2021-08-29","recovered_%":1.78,"new_case_%":1.41},{"Date":"2021-08-30","recovered_%":1.45,"new_case_%":1.34},{"Date":"2021-08-31","recovered_%":1.6,"new_case_%":1.22},{"Date":"2021-09-01","recovered_%":1.56,"new_case_%":1.21},{"Date":"2021-09-02","recovered_%":1.45,"new_case_%":1.21},{"Date":"2021-09-03","recovered_%":1.46,"new_case_%":1.17},{"Date":"2021-09-04","recovered_%":1.61,"new_case_%":1.26},{"Date":"2021-09-05","recovered_%":1.43,"new_case_%":1.21},{"Date":"2021-09-06","recovered_%":1.34,"new_case_%":1.08},{"Date":"2021-09-07","recovered_%":1.28,"new_case_%":1.06},{"Date":"2021-09-08","recovered_%":1.27,"new_case_%":1.07},{"Date":"2021-09-09","recovered_%":1.15,"new_case_%":1.2},{"Date":"2021-09-10","recovered_%":1.15,"new_case_%":1.06},{"Date":"2021-09-11","recovered_%":1.37,"new_case_%":1.11},{"Date":"2021-09-12","recovered_%":1.14,"new_case_%":1.01},{"Date":"2021-09-13","recovered_%":1.17,"new_case_%":0.9},{"Date":"2021-09-14","recovered_%":1.05,"new_case_%":0.84},{"Date":"2021-09-15","recovered_%":1.0,"new_case_%":0.97},{"Date":"2021-09-16","recovered_%":0.94,"new_case_%":0.97},{"Date":"2021-09-17","recovered_%":0.94,"new_case_%":1.0},{"Date":"2021-09-18","recovered_%":0.91,"new_case_%":0.96},{"Date":"2021-09-19","recovered_%":0.85,"new_case_%":0.92},{"Date":"2021-09-20","recovered_%":0.75,"new_case_%":0.85},{"Date":"2021-09-21","recovered_%":0.78,"new_case_%":0.73},{"Date":"2021-09-22","recovered_%":0.91,"new_case_%":0.74},{"Date":"2021-09-23","recovered_%":0.91,"new_case_%":0.87},{"Date":"2021-09-24","recovered_%":0.88,"new_case_%":0.83},{"Date":"2021-09-25","recovered_%":0.95,"new_case_%":0.77},{"Date":"2021-09-26","recovered_%":0.92,"new_case_%":0.79},{"Date":"2021-09-27","recovered_%":0.79,"new_case_%":0.65},{"Date":"2021-09-28","recovered_%":0.81,"new_case_%":0.6},{"Date":"2021-09-29","recovered_%":0.73,"new_case_%":0.65},{"Date":"2021-09-30","recovered_%":0.68,"new_case_%":0.73},{"Date":"2021-10-01","recovered_%":0.77,"new_case_%":0.73},{"Date":"2021-10-02","recovered_%":0.81,"new_case_%":0.7},{"Date":"2021-10-03","recovered_%":0.73,"new_case_%":0.66},{"Date":"2021-10-04","recovered_%":0.75,"new_case_%":0.6},{"Date":"2021-10-05","recovered_%":0.67,"new_case_%":0.6},{"Date":"2021-10-06","recovered_%":0.61,"new_case_%":0.59},{"Date":"2021-10-07","recovered_%":0.6,"new_case_%":0.67},{"Date":"2021-10-08","recovered_%":0.59,"new_case_%":0.66},{"Date":"2021-10-09","recovered_%":0.62,"new_case_%":0.63},{"Date":"2021-10-10","recovered_%":0.58,"new_case_%":0.63},{"Date":"2021-10-11","recovered_%":0.62,"new_case_%":0.58},{"Date":"2021-10-12","recovered_%":0.66,"new_case_%":0.55},{"Date":"2021-10-13","recovered_%":0.63,"new_case_%":0.58},{"Date":"2021-10-14","recovered_%":0.59,"new_case_%":0.64},{"Date":"2021-10-15","recovered_%":0.61,"new_case_%":0.6},{"Date":"2021-10-16","recovered_%":0.61,"new_case_%":0.6},{"Date":"2021-10-17","recovered_%":0.58,"new_case_%":0.61},{"Date":"2021-10-18","recovered_%":0.59,"new_case_%":0.56},{"Date":"2021-10-19","recovered_%":0.6,"new_case_%":0.51},{"Date":"2021-10-20","recovered_%":0.6,"new_case_%":0.49},{"Date":"2021-10-21","recovered_%":0.55,"new_case_%":0.53},{"Date":"2021-10-22","recovered_%":0.57,"new_case_%":0.54},{"Date":"2021-10-23","recovered_%":0.55,"new_case_%":0.53},{"Date":"2021-10-24","recovered_%":0.55,"new_case_%":0.51},{"Date":"2021-10-25","recovered_%":0.52,"new_case_%":0.47},{"Date":"2021-10-26","recovered_%":0.51,"new_case_%":0.41},{"Date":"2021-10-27","recovered_%":0.45,"new_case_%":0.45},{"Date":"2021-10-28","recovered_%":0.45,"new_case_%":0.51},{"Date":"2021-10-29","recovered_%":0.46,"new_case_%":0.47},{"Date":"2021-10-30","recovered_%":0.44,"new_case_%":0.48},{"Date":"2021-10-31","recovered_%":0.43,"new_case_%":0.46},{"Date":"2021-11-01","recovered_%":0.5,"new_case_%":0.43},{"Date":"2021-11-02","recovered_%":0.43,"new_case_%":0.39},{"Date":"2021-11-03","recovered_%":0.44,"new_case_%":0.4},{"Date":"2021-11-04","recovered_%":0.41,"new_case_%":0.41},{"Date":"2021-11-05","recovered_%":0.42,"new_case_%":0.42},{"Date":"2021-11-06","recovered_%":0.42,"new_case_%":0.43},{"Date":"2021-11-07","recovered_%":0.35,"new_case_%":0.4},{"Date":"2021-11-08","recovered_%":0.38,"new_case_%":0.38},{"Date":"2021-11-09","recovered_%":0.4,"new_case_%":0.35},{"Date":"2021-11-10","recovered_%":0.39,"new_case_%":0.35},{"Date":"2021-11-11","recovered_%":0.37,"new_case_%":0.38},{"Date":"2021-11-12","recovered_%":0.39,"new_case_%":0.36},{"Date":"2021-11-13","recovered_%":0.37,"new_case_%":0.35},{"Date":"2021-11-14","recovered_%":0.34,"new_case_%":0.35},{"Date":"2021-11-15","recovered_%":0.38,"new_case_%":0.31},{"Date":"2021-11-16","recovered_%":0.39,"new_case_%":0.29},{"Date":"2021-11-17","recovered_%":0.35,"new_case_%":0.32},{"Date":"2021-11-18","recovered_%":0.37,"new_case_%":0.34},{"Date":"2021-11-19","recovered_%":0.37,"new_case_%":0.33},{"Date":"2021-11-20","recovered_%":0.41,"new_case_%":0.32},{"Date":"2021-11-21","recovered_%":0.37,"new_case_%":0.34},{"Date":"2021-11-22","recovered_%":0.38,"new_case_%":0.31},{"Date":"2021-11-23","recovered_%":0.37,"new_case_%":0.25},{"Date":"2021-11-24","recovered_%":0.35,"new_case_%":0.28},{"Date":"2021-11-25","recovered_%":0.35,"new_case_%":0.3},{"Date":"2021-11-26","recovered_%":0.33,"new_case_%":0.31},{"Date":"2021-11-27","recovered_%":0.31,"new_case_%":0.29},{"Date":"2021-11-28","recovered_%":0.3,"new_case_%":0.28},{"Date":"2021-11-29","recovered_%":0.29,"new_case_%":0.23},{"Date":"2021-11-30","recovered_%":0.3,"new_case_%":0.2},{"Date":"2021-12-01","recovered_%":0.3,"new_case_%":0.23},{"Date":"2021-12-02","recovered_%":0.25,"new_case_%":0.23},{"Date":"2021-12-03","recovered_%":0.27,"new_case_%":0.23},{"Date":"2021-12-04","recovered_%":0.27,"new_case_%":0.28},{"Date":"2021-12-05","recovered_%":0.29,"new_case_%":0.22},{"Date":"2021-12-06","recovered_%":0.3,"new_case_%":0.19},{"Date":"2021-12-07","recovered_%":0.28,"new_case_%":0.16},{"Date":"2021-12-08","recovered_%":0.27,"new_case_%":0.17},{"Date":"2021-12-09","recovered_%":0.37,"new_case_%":0.19}]'

In [23]:
data[0]

{'txn_date': '2021-04-01',
 'new_case': 26,
 'total_case': 28889,
 'new_case_excludeabroad': 21,
 'total_case_excludeabroad': 25800,
 'new_death': 0,
 'total_death': 94,
 'new_recovered': 122,
 'total_recovered': 27767,
 'update_date': '2021-09-01 07:40:49'}

In [24]:
import pandas as pd
g = pd.read_json(json_data)
type(g)

pandas.core.frame.DataFrame

In [25]:
g['Date']

0     2021-04-01
1     2021-04-02
2     2021-04-03
3     2021-04-04
4     2021-04-05
         ...
248   2021-12-05
249   2021-12-06
250   2021-12-07
251   2021-12-08
252   2021-12-09
Name: Date, Length: 253, dtype: datetime64[ns]

In [26]:
for i,row in g.iterrows():
    print(tuple(row))

(Timestamp('2021-04-01 00:00:00'), 0.42, 0.09)
(Timestamp('2021-04-02 00:00:00'), 0.2, 0.2)
(Timestamp('2021-04-03 00:00:00'), 0.21, 0.29)
(Timestamp('2021-04-04 00:00:00'), 0.36, 0.33)
(Timestamp('2021-04-05 00:00:00'), 0.23, 0.66)
(Timestamp('2021-04-06 00:00:00'), 0.37, 0.85)
(Timestamp('2021-04-07 00:00:00'), 0.4, 1.12)
(Timestamp('2021-04-08 00:00:00'), 0.11, 1.34)
(Timestamp('2021-04-09 00:00:00'), 0.09, 1.81)
(Timestamp('2021-04-10 00:00:00'), 0.1, 2.49)
(Timestamp('2021-04-11 00:00:00'), 0.16, 2.96)
(Timestamp('2021-04-12 00:00:00'), 0.1, 2.93)
(Timestamp('2021-04-13 00:00:00'), 0.12, 2.79)
(Timestamp('2021-04-14 00:00:00'), 0.09, 3.73)
(Timestamp('2021-04-15 00:00:00'), 0.16, 4.12)
(Timestamp('2021-04-16 00:00:00'), 0.25, 4.05)
(Timestamp('2021-04-17 00:00:00'), 0.22, 3.81)
(Timestamp('2021-04-18 00:00:00'), 0.27, 4.17)
(Timestamp('2021-04-19 00:00:00'), 0.24, 3.18)
(Timestamp('2021-04-20 00:00:00'), 0.38, 3.19)
(Timestamp('2021-04-21 00:00:00'), 0.89, 3.13)
(Timestamp('2021-04-22 00:00:00'), 0.99, 3.06)
(Timestamp('2021-04-23 00:00:00'), 0.68, 4.12)
(Timestamp('2021-04-24 00:00:00'), 0.71, 5.35)
(Timestamp('2021-04-25 00:00:00'), 0.99, 4.4)
(Timestamp('2021-04-26 00:00:00'), 0.8300000000000001, 3.56)
(Timestamp('2021-04-27 00:00:00'), 3.2800000000000002, 3.65)
(Timestamp('2021-04-28 00:00:00'), 1.38, 3.26)
(Timestamp('2021-04-29 00:00:00'), 1.56, 2.94)
(Timestamp('2021-04-30 00:00:00'), 1.32, 2.43)
(Timestamp('2021-05-01 00:00:00'), 2.7199999999999998, 2.8200000000000003)
(Timestamp('2021-05-02 00:00:00'), 1.71, 2.81)
(Timestamp('2021-05-03 00:00:00'), 2.43, 2.87)
(Timestamp('2021-05-04 00:00:00'), 2.05, 2.42)
(Timestamp('2021-05-05 00:00:00'), 2.52, 2.8200000000000003)
(Timestamp('2021-05-06 00:00:00'), 3.17, 2.49)
(Timestamp('2021-05-07 00:00:00'), 3.01, 2.59)
(Timestamp('2021-05-08 00:00:00'), 2.76, 2.98)
(Timestamp('2021-05-09 00:00:00'), 2.62, 2.52)
(Timestamp('2021-05-10 00:00:00'), 1.8900000000000001, 1.92)
(Timestamp('2021-05-11 00:00:00'), 2.1, 2.21)
(Timestamp('2021-05-12 00:00:00'), 2.26, 2.23)
(Timestamp('2021-05-13 00:00:00'), 1.6800000000000002, 5.21)
(Timestamp('2021-05-14 00:00:00'), 1.77, 2.35)
(Timestamp('2021-05-15 00:00:00'), 1.3599999999999999, 3.12)
(Timestamp('2021-05-16 00:00:00'), 2.11, 2.27)
(Timestamp('2021-05-17 00:00:00'), 1.26, 8.67)
(Timestamp('2021-05-18 00:00:00'), 2.39, 2.18)
(Timestamp('2021-05-19 00:00:00'), 3.81, 2.9)
(Timestamp('2021-05-20 00:00:00'), 1.9, 2.2)
(Timestamp('2021-05-21 00:00:00'), 2.33, 2.83)
(Timestamp('2021-05-22 00:00:00'), 2.3, 2.42)
(Timestamp('2021-05-23 00:00:00'), 1.65, 2.61)
(Timestamp('2021-05-24 00:00:00'), 1.18, 2.05)
(Timestamp('2021-05-25 00:00:00'), 2.2800000000000002, 2.38)
(Timestamp('2021-05-26 00:00:00'), 1.8599999999999999, 1.78)
(Timestamp('2021-05-27 00:00:00'), 1.46, 2.35)
(Timestamp('2021-05-28 00:00:00'), 2.79, 2.59)
(Timestamp('2021-05-29 00:00:00'), 2.96, 3.21)
(Timestamp('2021-05-30 00:00:00'), 1.9, 2.93)
(Timestamp('2021-05-31 00:00:00'), 1.94, 3.43)
(Timestamp('2021-06-01 00:00:00'), 2.09, 1.38)
(Timestamp('2021-06-02 00:00:00'), 1.72, 2.08)
(Timestamp('2021-06-03 00:00:00'), 2.14, 2.29)
(Timestamp('2021-06-04 00:00:00'), 1.45, 1.53)
(Timestamp('2021-06-05 00:00:00'), 1.94, 1.6099999999999999)
(Timestamp('2021-06-06 00:00:00'), 1.37, 1.51)
(Timestamp('2021-06-07 00:00:00'), 1.67, 1.34)
(Timestamp('2021-06-08 00:00:00'), 1.3599999999999999, 1.46)
(Timestamp('2021-06-09 00:00:00'), 2.3, 1.45)
(Timestamp('2021-06-10 00:00:00'), 1.62, 1.23)
(Timestamp('2021-06-11 00:00:00'), 3.01, 1.21)
(Timestamp('2021-06-12 00:00:00'), 2.73, 1.7000000000000002)
(Timestamp('2021-06-13 00:00:00'), 2.11, 1.43)
(Timestamp('2021-06-14 00:00:00'), 1.77, 1.6800000000000002)
(Timestamp('2021-06-15 00:00:00'), 2.36, 1.48)
(Timestamp('2021-06-16 00:00:00'), 2.42, 1.1400000000000001)
(Timestamp('2021-06-17 00:00:00'), 2.24, 1.51)
(Timestamp('2021-06-18 00:00:00'), 1.94, 1.45)
(Timestamp('2021-06-19 00:00:00'), 2.31, 1.71)
(Timestamp('2021-06-20 00:00:00'), 1.1, 1.69)
(Timestamp('2021-06-21 00:00:00'), 0.92, 1.43)
(Timestamp('2021-06-22 00:00:00'), 0.91, 1.8)
(Timestamp('2021-06-23 00:00:00'), 0.85, 1.3900000000000001)
(Timestamp('2021-06-24 00:00:00'), 0.68, 1.77)
(Timestamp('2021-06-25 00:00:00'), 0.74, 1.54)
(Timestamp('2021-06-26 00:00:00'), 1.48, 1.73)
(Timestamp('2021-06-27 00:00:00'), 0.92, 1.63)
(Timestamp('2021-06-28 00:00:00'), 1.34, 2.16)
(Timestamp('2021-06-29 00:00:00'), 1.1, 1.83)
(Timestamp('2021-06-30 00:00:00'), 0.93, 1.85)
(Timestamp('2021-07-01 00:00:00'), 1.22, 2.09)
(Timestamp('2021-07-02 00:00:00'), 1.34, 2.25)
(Timestamp('2021-07-03 00:00:00'), 1.1400000000000001, 2.25)
(Timestamp('2021-07-04 00:00:00'), 1.2, 2.09)
(Timestamp('2021-07-05 00:00:00'), 0.88, 2.13)
(Timestamp('2021-07-06 00:00:00'), 1.22, 1.8399999999999999)
(Timestamp('2021-07-07 00:00:00'), 1.38, 2.16)
(Timestamp('2021-07-08 00:00:00'), 1.62, 2.29)
(Timestamp('2021-07-09 00:00:00'), 1.24, 2.92)
(Timestamp('2021-07-10 00:00:00'), 1.18, 2.85)
(Timestamp('2021-07-11 00:00:00'), 1.2, 2.84)
(Timestamp('2021-07-12 00:00:00'), 1.07, 2.51)
(Timestamp('2021-07-13 00:00:00'), 1.07, 2.46)
(Timestamp('2021-07-14 00:00:00'), 1.4100000000000001, 2.5700000000000003)
(Timestamp('2021-07-15 00:00:00'), 1.49, 2.47)
(Timestamp('2021-07-16 00:00:00'), 1.5, 2.54)
(Timestamp('2021-07-17 00:00:00'), 1.6099999999999999, 2.5700000000000003)
(Timestamp('2021-07-18 00:00:00'), 1.42, 2.83)
(Timestamp('2021-07-19 00:00:00'), 1.38, 2.84)
(Timestamp('2021-07-20 00:00:00'), 1.54, 2.65)
(Timestamp('2021-07-21 00:00:00'), 1.88, 2.96)
(Timestamp('2021-07-22 00:00:00'), 1.75, 3.01)
(Timestamp('2021-07-23 00:00:00'), 1.6600000000000001, 3.12)
(Timestamp('2021-07-24 00:00:00'), 1.58, 2.96)
(Timestamp('2021-07-25 00:00:00'), 1.3900000000000001, 3.08)
(Timestamp('2021-07-26 00:00:00'), 1.32, 3.0)
(Timestamp('2021-07-27 00:00:00'), 1.74, 2.69)
(Timestamp('2021-07-28 00:00:00'), 1.85, 3.04)
(Timestamp('2021-07-29 00:00:00'), 1.75, 3.15)
(Timestamp('2021-07-30 00:00:00'), 1.85, 3.0)
(Timestamp('2021-07-31 00:00:00'), 1.8, 3.17)
(Timestamp('2021-08-01 00:00:00'), 2.18, 2.93)
(Timestamp('2021-08-02 00:00:00'), 2.2, 2.84)
(Timestamp('2021-08-03 00:00:00'), 2.85, 2.9)
(Timestamp('2021-08-04 00:00:00'), 2.67, 3.0)
(Timestamp('2021-08-05 00:00:00'), 2.59, 3.02)
(Timestamp('2021-08-06 00:00:00'), 3.1, 2.99)
(Timestamp('2021-08-07 00:00:00'), 2.87, 2.9699999999999998)
(Timestamp('2021-08-08 00:00:00'), 2.45, 2.64)
(Timestamp('2021-08-09 00:00:00'), 2.55, 2.5300000000000002)
(Timestamp('2021-08-10 00:00:00'), 2.87, 2.49)
(Timestamp('2021-08-11 00:00:00'), 2.69, 2.58)
(Timestamp('2021-08-12 00:00:00'), 2.8200000000000003, 2.71)
(Timestamp('2021-08-13 00:00:00'), 2.33, 2.71)
(Timestamp('2021-08-14 00:00:00'), 2.67, 2.49)
(Timestamp('2021-08-15 00:00:00'), 2.33, 2.41)
(Timestamp('2021-08-16 00:00:00'), 2.26, 2.2800000000000002)
(Timestamp('2021-08-17 00:00:00'), 2.19, 2.12)
(Timestamp('2021-08-18 00:00:00'), 2.34, 2.12)
(Timestamp('2021-08-19 00:00:00'), 2.24, 2.11)
(Timestamp('2021-08-20 00:00:00'), 2.03, 1.97)
(Timestamp('2021-08-21 00:00:00'), 2.25, 2.0)
(Timestamp('2021-08-22 00:00:00'), 1.97, 1.81)
(Timestamp('2021-08-23 00:00:00'), 2.07, 1.6400000000000001)
(Timestamp('2021-08-24 00:00:00'), 1.85, 1.58)
(Timestamp('2021-08-25 00:00:00'), 1.92, 1.67)
(Timestamp('2021-08-26 00:00:00'), 1.8399999999999999, 1.65)
(Timestamp('2021-08-27 00:00:00'), 1.77, 1.6400000000000001)
(Timestamp('2021-08-28 00:00:00'), 1.77, 1.55)
(Timestamp('2021-08-29 00:00:00'), 1.78, 1.4100000000000001)
(Timestamp('2021-08-30 00:00:00'), 1.45, 1.34)
(Timestamp('2021-08-31 00:00:00'), 1.6, 1.22)
(Timestamp('2021-09-01 00:00:00'), 1.56, 1.21)
(Timestamp('2021-09-02 00:00:00'), 1.45, 1.21)
(Timestamp('2021-09-03 00:00:00'), 1.46, 1.17)
(Timestamp('2021-09-04 00:00:00'), 1.6099999999999999, 1.26)
(Timestamp('2021-09-05 00:00:00'), 1.43, 1.21)
(Timestamp('2021-09-06 00:00:00'), 1.34, 1.08)
(Timestamp('2021-09-07 00:00:00'), 1.28, 1.06)
(Timestamp('2021-09-08 00:00:00'), 1.27, 1.07)
(Timestamp('2021-09-09 00:00:00'), 1.15, 1.2)
(Timestamp('2021-09-10 00:00:00'), 1.15, 1.06)
(Timestamp('2021-09-11 00:00:00'), 1.37, 1.11)
(Timestamp('2021-09-12 00:00:00'), 1.1400000000000001, 1.01)
(Timestamp('2021-09-13 00:00:00'), 1.17, 0.9)
(Timestamp('2021-09-14 00:00:00'), 1.05, 0.84)
(Timestamp('2021-09-15 00:00:00'), 1.0, 0.97)
(Timestamp('2021-09-16 00:00:00'), 0.9400000000000001, 0.97)
(Timestamp('2021-09-17 00:00:00'), 0.9400000000000001, 1.0)
(Timestamp('2021-09-18 00:00:00'), 0.91, 0.96)
(Timestamp('2021-09-19 00:00:00'), 0.85, 0.92)
(Timestamp('2021-09-20 00:00:00'), 0.75, 0.85)
(Timestamp('2021-09-21 00:00:00'), 0.78, 0.73)
(Timestamp('2021-09-22 00:00:00'), 0.91, 0.74)
(Timestamp('2021-09-23 00:00:00'), 0.91, 0.87)
(Timestamp('2021-09-24 00:00:00'), 0.88, 0.8300000000000001)
(Timestamp('2021-09-25 00:00:00'), 0.9500000000000001, 0.77)
(Timestamp('2021-09-26 00:00:00'), 0.92, 0.79)
(Timestamp('2021-09-27 00:00:00'), 0.79, 0.65)
(Timestamp('2021-09-28 00:00:00'), 0.81, 0.6000000000000001)
(Timestamp('2021-09-29 00:00:00'), 0.73, 0.65)
(Timestamp('2021-09-30 00:00:00'), 0.68, 0.73)
(Timestamp('2021-10-01 00:00:00'), 0.77, 0.73)
(Timestamp('2021-10-02 00:00:00'), 0.81, 0.7000000000000001)
(Timestamp('2021-10-03 00:00:00'), 0.73, 0.66)
(Timestamp('2021-10-04 00:00:00'), 0.75, 0.6000000000000001)
(Timestamp('2021-10-05 00:00:00'), 0.67, 0.6000000000000001)
(Timestamp('2021-10-06 00:00:00'), 0.61, 0.59)
(Timestamp('2021-10-07 00:00:00'), 0.6000000000000001, 0.67)
(Timestamp('2021-10-08 00:00:00'), 0.59, 0.66)
(Timestamp('2021-10-09 00:00:00'), 0.62, 0.63)
(Timestamp('2021-10-10 00:00:00'), 0.58, 0.63)
(Timestamp('2021-10-11 00:00:00'), 0.62, 0.58)
(Timestamp('2021-10-12 00:00:00'), 0.66, 0.55)
(Timestamp('2021-10-13 00:00:00'), 0.63, 0.58)
(Timestamp('2021-10-14 00:00:00'), 0.59, 0.64)
(Timestamp('2021-10-15 00:00:00'), 0.61, 0.6000000000000001)
(Timestamp('2021-10-16 00:00:00'), 0.61, 0.6000000000000001)
(Timestamp('2021-10-17 00:00:00'), 0.58, 0.61)
(Timestamp('2021-10-18 00:00:00'), 0.59, 0.56)
(Timestamp('2021-10-19 00:00:00'), 0.6000000000000001, 0.51)
(Timestamp('2021-10-20 00:00:00'), 0.6000000000000001, 0.49)
(Timestamp('2021-10-21 00:00:00'), 0.55, 0.53)
(Timestamp('2021-10-22 00:00:00'), 0.5700000000000001, 0.54)
(Timestamp('2021-10-23 00:00:00'), 0.55, 0.53)
(Timestamp('2021-10-24 00:00:00'), 0.55, 0.51)
(Timestamp('2021-10-25 00:00:00'), 0.52, 0.47000000000000003)
(Timestamp('2021-10-26 00:00:00'), 0.51, 0.41000000000000003)
(Timestamp('2021-10-27 00:00:00'), 0.45, 0.45)
(Timestamp('2021-10-28 00:00:00'), 0.45, 0.51)
(Timestamp('2021-10-29 00:00:00'), 0.46, 0.47000000000000003)
(Timestamp('2021-10-30 00:00:00'), 0.44, 0.48)
(Timestamp('2021-10-31 00:00:00'), 0.43, 0.46)
(Timestamp('2021-11-01 00:00:00'), 0.5, 0.43)
(Timestamp('2021-11-02 00:00:00'), 0.43, 0.39)
(Timestamp('2021-11-03 00:00:00'), 0.44, 0.4)
(Timestamp('2021-11-04 00:00:00'), 0.41000000000000003, 0.41000000000000003)
(Timestamp('2021-11-05 00:00:00'), 0.42, 0.42)
(Timestamp('2021-11-06 00:00:00'), 0.42, 0.43)
(Timestamp('2021-11-07 00:00:00'), 0.35000000000000003, 0.4)
(Timestamp('2021-11-08 00:00:00'), 0.38, 0.38)
(Timestamp('2021-11-09 00:00:00'), 0.4, 0.35000000000000003)
(Timestamp('2021-11-10 00:00:00'), 0.39, 0.35000000000000003)
(Timestamp('2021-11-11 00:00:00'), 0.37, 0.38)
(Timestamp('2021-11-12 00:00:00'), 0.39, 0.36)
(Timestamp('2021-11-13 00:00:00'), 0.37, 0.35000000000000003)
(Timestamp('2021-11-14 00:00:00'), 0.34, 0.35000000000000003)
(Timestamp('2021-11-15 00:00:00'), 0.38, 0.31)
(Timestamp('2021-11-16 00:00:00'), 0.39, 0.29)
(Timestamp('2021-11-17 00:00:00'), 0.35000000000000003, 0.32)
(Timestamp('2021-11-18 00:00:00'), 0.37, 0.34)
(Timestamp('2021-11-19 00:00:00'), 0.37, 0.33)
(Timestamp('2021-11-20 00:00:00'), 0.41000000000000003, 0.32)
(Timestamp('2021-11-21 00:00:00'), 0.37, 0.34)
(Timestamp('2021-11-22 00:00:00'), 0.38, 0.31)
(Timestamp('2021-11-23 00:00:00'), 0.37, 0.25)
(Timestamp('2021-11-24 00:00:00'), 0.35000000000000003, 0.28)
(Timestamp('2021-11-25 00:00:00'), 0.35000000000000003, 0.30000000000000004)
(Timestamp('2021-11-26 00:00:00'), 0.33, 0.31)
(Timestamp('2021-11-27 00:00:00'), 0.31, 0.29)
(Timestamp('2021-11-28 00:00:00'), 0.30000000000000004, 0.28)
(Timestamp('2021-11-29 00:00:00'), 0.29, 0.23)
(Timestamp('2021-11-30 00:00:00'), 0.30000000000000004, 0.2)
(Timestamp('2021-12-01 00:00:00'), 0.30000000000000004, 0.23)
(Timestamp('2021-12-02 00:00:00'), 0.25, 0.23)
(Timestamp('2021-12-03 00:00:00'), 0.27, 0.23)
(Timestamp('2021-12-04 00:00:00'), 0.27, 0.28)
(Timestamp('2021-12-05 00:00:00'), 0.29, 0.22)
(Timestamp('2021-12-06 00:00:00'), 0.30000000000000004, 0.19)
(Timestamp('2021-12-07 00:00:00'), 0.28, 0.16)
(Timestamp('2021-12-08 00:00:00'), 0.27, 0.17)
(Timestamp('2021-12-09 00:00:00'), 0.37, 0.19)